import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Generated by FlutterFire CLI when `google-services.json` is present.
/// Replace placeholders after running:
/// `flutterfire configure --project=<firebase-project-id>`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported for pux.');
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS is not configured yet.');
      default:
        throw UnsupportedError('Unsupported platform for Firebase.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY', defaultValue: 'REPLACE_ME'),
    appId: String.fromEnvironment('FIREBASE_APP_ID', defaultValue: 'REPLACE_ME'),
    messagingSenderId:
        String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: 'REPLACE_ME'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'REPLACE_ME'),
    storageBucket:
        String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'REPLACE_ME'),
  );
}
